chanceCardList = ["start",
                  "red1",
                  "purple1",
                  "utility",
                  "railroad",
                  "railroad",
                  "threeBack",
                  "prison",
                  "0",
                  "0",
                  "0",
                  "0",
                  "0",
                  "0",
                  "0",
                  "0",
                  "0"]
